### ISSUE TITLE
iPhone 6S 

### ISSUE THREAD

**Issue by Antoniochavez17** [iabem97/topanga#15]
Failed to jailbreaking in iOS 11.1.1

**Comment by M3m0ryH4ck3r** [comment]
Does your phone have the TSMC A9 chip or the Samsung made A9?

**Comment by witt2witty** [comment]
I've tried on the 5S and a Samsung 6S Plus. It fails every time for me

**Comment by Antoniochavez17** [comment]
Not sure about that how I can find out how’s?

**Comment by Antoniochavez17** [comment]
I found out it Samsung-manufactured A9 processor on my iPhone 6S

**Comment by witt2witty** [comment]
Same, I can't get it to run

**Comment by Ctodaz** [comment]
Same on 6s iOS 11.1.2 with N71AP...Jailbreak...failed

**Comment by abdul5252** [comment]
topanga not work in iphone 6s
