### ISSUE TITLE
Uikit installation crash 

### ISSUE THREAD

**Issue by iM4CH3T3** [iabem97/topanga#17]

**Comment by iM4CH3T3** [comment]
After reboot when I rerun the app it creates a crash.
It seems it has something to do with patchy and uikittool.
Also they’re marked red in cydia.
Log:
https://www.dropbox.com/s/12yu5sv4imzhucu/topanga-2017-12-23-205308.ips?dl=0

**Comment by iabem97** [comment]
Cydia is no longer used in to.panga. Closing.
