### ISSUE TITLE
Iphone 6 iOS 11.1.2 no Cydia

### ISSUE THREAD

**Issue by rezzifriaz** [iabem97/topanga#2]

**Comment by iM4CH3T3** [comment]
Can you please check if you have the bootstrap folder installed by this jailbreak ? For me it’s not. So it can’t even do anything because everything starts from the bootstrap folder :/

**Comment by iM4CH3T3** [comment]
Location is in /

**Comment by HonestlyAnnoying** [comment]
bootstrap is installed, but no Cydia icon

**Comment by rezzifriaz** [comment]
No bootstrap folder,why ?

**Comment by Basputaek13** [comment]
Follow

**Comment by Basputaek13** [comment]
Follow

**Comment by iM4CH3T3** [comment]
Because when no bootstrap folder the cydia.tar can’t be extracted and installed

**Comment by nullpixel** [comment]
Hi there, we've closed this issue as a dupe of #1.
