### ISSUE TITLE
Claims to succeed, but doesn't actually install cydia (J81AP)

### ISSUE THREAD

**Issue by 916253** [iabem97/topanga#21]
output while running: https://hastebin.com/ecezovutoz.xml
I'd be happy to provide any more information that could be useful

**Comment by SteBowker10** [comment]
Update to latest version of the project. You need to edit jailbreak.m file, go to code line 266 and make sure if(should_install_cydia == YES)

Feel free to Close

**Comment by aayyoub977** [comment]
any tutorial how to install it?

**Comment by SteBowker10** [comment]
I’ve complied it for you. Proceed with this iPA instead with the updated jailbreak.m file. Download and use this: https://www.dropbox.com/s/avfj015pw7c9w14/topanga.ipa

**Comment by Kurrokage** [comment]
Hey SteBowker10 would you happen to have a backup of that to.panga ipa? looking for one that actually injects Cydia

**Comment by 916253** [comment]
@SteBowker10's suggestion causes cydia to install, although it fails to execute. Despite this, that is outside the scope of this issue, so i'm closing it for now
