### ISSUE TITLE
iPhone 6s 11.1.2 N71mAP-not working

### ISSUE THREAD

**Issue by NathanMayor** [iabem97/topanga#24]
Currently not working for iPhone 6s on 11.1.2 with the N71mAP chip

**Comment by ctabuyo** [comment]
@NathanMayor Check for solution in the "Closed issues" section.

**Comment by NathanMayor** [comment]
I have looked can’t find it

**Comment by priiml** [comment]
@NathanMayor https://github.com/iabem97/topanga/issues/4

**Comment by NathanMayor** [comment]
I don’t know how to do that

**Comment by priiml** [comment]
Then you shouldn't be messing with this. It's unstable for **developers**.

**Comment by NathanMayor** [comment]
Calm Yourself bro it ain’t that deep

**Comment by priiml** [comment]
Just telling you, wait for a stable JB.I know its exciting but you don't wanna brick your device.

**Comment by NathanMayor** [comment]
I get you bro. Just looking for answers to my problems, seems there are no easy solutions yet. Cheers for the clarification.

**Comment by priiml** [comment]
https://github.com/iabem97/topanga/issues/19 @Matrons97 posted an IPA but I can't verify the validity of it

**Comment by mharris3960** [comment]
Guys, wait for a stable one. You don't want a stuffed phone for Christmas then lose a jailbreak on top of that.

**Comment by abdul5252** [comment]
when stable ver. release??
