### ISSUE TITLE
Where can I find bootstrap.tar source code?

### ISSUE THREAD

**Issue by Co2333** [iabem97/topanga#25]
I'm new here...............................QAQ
and also wish to learn and understand this codes.
this days my friend told me that saurik updates cydia  often-ly,and I wand to keep up to date.
so where can I find bootstrap.tar ? 
Thanks.

**Comment by MrARM** [comment]
```tar –xzf bootstrap.tar```

you notice it's just a few compiled unix binaries inside it.
