### ISSUE TITLE
iPhone 8 (D201AP) on 11.1.2 says finished, but no Cydia

### ISSUE THREAD

**Issue by kooz123** [iabem97/topanga#29]
Log: https://ghostbin.com/paste/jqfoe
Have tried multiple reboots, erases, etc and nothing seems to work. After to.panga says it's finished, Xcode debugger starts bouncing around these errors: 
tfp0 read failed (os/kern) invalid address addr: 0x367 err:1 port:188900b
tfp0 read failed (os/kern) invalid address 

Thanks in advance!

**Comment by leoskingsley** [comment]
It appears that a logic error preventing cydia from installing is still present in the latest version. It's a simple fix.

In line 266, jailbreak.m (extra_recipe), change `if(should_install_cydia != YES) {` to `if(should_install_cydia == YES) {`. This fixed it for me on iPhone 7 iOS 11.1.2. If not, I'll take a deeper look into the log for you.
