### ISSUE TITLE
How to find structure Offsets for iOS 11.0.3/15A432

### ISSUE THREAD

**Issue by snowleopardw** [iabem97/topanga#32]
hello i would like to contribute, how can i find build structure offests?

**Comment by ctabuyo** [comment]
@snowleopardw Decompiling the kernel of the corresponding iOS version. Please close this issues as it is not "an issue" by definition. Thanks!

**Comment by snowleopardw** [comment]
@ctabuyo Thank you for your help! Got that. Could you tell me a little bit more about how to decompile the iOS 11 ipsw file? I know how to decompile the iOS 10 one ( https://gist.github.com/uroboro/5b2b2b2aa1793132c4e91826ce844957 ). If there is a step-to-step toturial, it will be so nice. Thank you so much!

**Comment by ctabuyo** [comment]
@snowleopardw It's same method as vortex ;)

**Comment by Co2333** [comment]
@ctabuyo 我他喵的到现在还不知道offset是什么鬼

**Comment by Co2333** [comment]
if it's about downgrade. better not to try.
I failed to >>>> iOS 11.1.2 --> iOS 10.2 
Specify  --no-bandboard but stacked.

**Comment by snowleopardw** [comment]
@ctabuyo To my knowledge, vortex requires the offset_blablabla, and async_wake needs the ksymbol_blablabla. It seems that async_wake needs more values than vortex. Please give me a hand, bro. Thank you so much!

**Comment by snowleopardw** [comment]
@Co2333 设备型号不同、iOS 版本不同，offset 就会不一样。6s 11.1.2 和 6s Plus 11.1.2 的 offset 值是不同的。具有自己设备型号 iOS 版本号的 offset 唯一值写入了越狱程序源代码，才会成功在自己的设备上运行。类似于对设备型号和 iOS 版本号做适配。

**Comment by Co2333** [comment]
谢谢。

**Comment by snowleopardw** [comment]
@Co2333 Use ReiBoot if you stuck in the recovery mode. You should add your offsets of your device/iOS version to the codes first.

**Comment by ctabuyo** [comment]
@snowleopardw To.panga没必要offsets还是symbols为运行

**Comment by snowleopardw** [comment]
@Co2333 不客气～

**Comment by snowleopardw** [comment]
@ctabuyo How to get symbols from iOS 11 ipsw file? I appreciate. The toturial only shows me how to get offsets from iOS 10 ipsw file.

**Comment by ctabuyo** [comment]
These are offsets for iOS 11:

```
int kstruct_offsets_15B202[] = {
  0xb,   // KSTRUCT_OFFSET_TASK_LCK_MTX_TYPE,
  0x10,  // KSTRUCT_OFFSET_TASK_REF_COUNT,
  0x14,  // KSTRUCT_OFFSET_TASK_ACTIVE,
  0x20,  // KSTRUCT_OFFSET_TASK_VM_MAP,
  0x28,  // KSTRUCT_OFFSET_TASK_NEXT,
  0x30,  // KSTRUCT_OFFSET_TASK_PREV,
  0x308, // KSTRUCT_OFFSET_TASK_ITK_SPACE
  0x368, // KSTRUCT_OFFSET_TASK_BSD_INFO,
  
  0x0,   // KSTRUCT_OFFSET_IPC_PORT_IO_BITS,
  0x4,   // KSTRUCT_OFFSET_IPC_PORT_IO_REFERENCES,
  0x40,  // KSTRUCT_OFFSET_IPC_PORT_IKMQ_BASE,
  0x50,  // KSTRUCT_OFFSET_IPC_PORT_MSG_COUNT,
  0x60,  // KSTRUCT_OFFSET_IPC_PORT_IP_RECEIVER,
  0x68,  // KSTRUCT_OFFSET_IPC_PORT_IP_KOBJECT,
  0x90,  // KSTRUCT_OFFSET_IPC_PORT_IP_CONTEXT,
  0xa0,  // KSTRUCT_OFFSET_IPC_PORT_IP_SRIGHTS,
  
  0x10,  // KSTRUCT_OFFSET_PROC_PID,
  0x26c, // KSTRUCT_OFFSET_PROC_COMM,
  
  0x20,  // KSTRUCT_OFFSET_IPC_SPACE_IS_TABLE
  
  0x180, // KSTRUCT_OFFSET_THREAD_BOUND_PROCESSOR
  0x188, // KSTRUCT_OFFSET_THREAD_LAST_PROCESSOR
  0x190, // KSTRUCT_OFFSET_THREAD_CHOSEN_PROCESSOR
  0x408, // KSTRUCT_OFFSET_THREAD_CONTEXT_DATA
  0x410, // KSTRUCT_OFFSET_THREAD_UPCB
  0x418, // KSTRUCT_OFFSET_THREAD_UNEON
  0x420, // KSTRUCT_OFFSET_THREAD_KSTACKPTR
  
  0x54,  // KSTRUCT_OFFSET_PROCESSOR_CPU_ID
  
  0x28,  // KSTRUCT_OFFSET_CPU_DATA_EXCEPSTACKPTR
  0X78,  // KSTRUCT_OFFSET_CPU_DATA_CPU_PROCESSOR
};
```

**Comment by snowleopardw** [comment]
@ctabuyo Thank you for posting the iOS 11 offsets. Please give me another hand, bro. What about the symbols of non-11.1.2? Thank you so much!

**Comment by ctabuyo** [comment]
@snowleopardw https://medium.com/@cji_/hunting-for-ios-kernel-symbols-e48a446bb00

I'm looking for developers to help me with a new jailbreak I'm coming up. I can speak Chinese, if you're up, let me know!

**Comment by Co2333** [comment]
@snowleopardw I saw the system log shows that:
Cleaning system volume. Done. 
Sending system data........0,10,20....................balabalabala Done.
Trying to balabalabala.......Failed.
Return  code....balabalabala. 
It’s too late to shut down the process,,

**Comment by snowleopardw** [comment]
@ctabuyo Sure. I will do my best to help you if you need, bro.

**Comment by ctabuyo** [comment]
@snowleopardw You can add me on WeChat, ctabuyo.

**Comment by nullpixel** [comment]
Closed as off topic
