### ISSUE TITLE
[Check Inside] Can someone pls send me .ipa?

### ISSUE THREAD

**Issue by SCNDRL** [iabem97/topanga#34]
Can anyone pls send me .ipa? With working cydia install and fix jailbreak “failed”? I have 6S Plus 11.1.2. I can’t figure it out my self, my macbook in service at the moment. Thanks

**Comment by tomlube** [comment]
No

**Comment by ctabuyo** [comment]
@SCNDRL No one will.

**Comment by Co2333** [comment]
https://pan.baidu.com/s/1bAbrqA
Upload time:17.12.24
as a cm gitf?

**Comment by nullpixel** [comment]
Closed as invalid
