### ISSUE TITLE
ncurses.h not found

### ISSUE THREAD

**Issue by mharris3960** [iabem97/topanga#41]
ncurses.h not found error on jailbreak.m line 247 : #include <ncurses.h>

**Comment by AaroniusLeonius** [comment]
Install the brew package manager from [https://brew.sh/](https://brew.sh/)
After that, run this command
`brew install ncurses`

It should compile after that.

**Comment by mharris3960** [comment]
Already Installed

**Comment by AaroniusLeonius** [comment]
Edit the build settings to search for headers in /usr/local/include

**Comment by mharris3960** [comment]
Done that but then gives me these : Implicit declaration of function 'sleep' is invalid in C99
Conflicting types for sleep
missing #include <unistd.h> declaration of sleep must be imported from module darwin knem.c

**Comment by AaroniusLeonius** [comment]
Try using the compile.sh script included.

**Comment by mharris3960** [comment]
ok

**Comment by yuzhouheike** [comment]
thx

**Comment by mharris3960** [comment]
The following build commands failed:
	CompileC build/topanga.build/Release-iphoneos/topanga.build/Objects-normal/arm64/jailbreak.o topanga/extra_recipe/jailbreak.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by yuzhouheike** [comment]
Edit the build settings：
SYSTEM_HEADER_SEARCH_PATHS =  /usr/local/opt/ncurses/include

**Comment by lecopsportif** [comment]
Solution from yuzhouheike did the trick !

**Comment by Johntpeterson** [comment]
yuzhouheike's solution worked perfectly.

**Comment by iabem97** [comment]
ncurses was added by mistake. last commit removes that line
