### ISSUE TITLE
How do you remove it from the iphone?

### ISSUE THREAD

**Issue by EpiJ** [iabem97/topanga#43]

**Comment by M3m0ryH4ck3r** [comment]
Just delete it from the springboard?

**Comment by M3m0ryH4ck3r** [comment]
Actually, are you loading it from Cydia-Impactor or loading it from XCode?

**Comment by TimVanDenEnden** [comment]
I installed with xcode now it install this weird jjjj app how can we remove it?

**Comment by yuzhouheike** [comment]
I have same question with you

**Comment by TimVanDenEnden** [comment]
Lets hope they have a answer for us :)

**Comment by TimVanDenEnden** [comment]
yuzhouheike does it run for you?

**Comment by EpiJ** [comment]
i did it with to.panga

**Comment by iM4CH3T3** [comment]
Why you install random stuff without to read the changelog first

**Comment by iM4CH3T3** [comment]
It isn’t safe to remove either cydia also jjjj because dpkg isn’t fixed 100%
Just stick with it and don’t touch anything till dpkg is fixed and read the changelog before doing anything...
Such reported issues aren’t helpful in any case...
