### ISSUE TITLE
ncurses.h file not found

### ISSUE THREAD

**Issue by ViroDaHaxr** [iabem97/topanga#44]
Previously it was tpf0 read failure as seen on my comment in another issue. Downloaded new commit you made and am seeing "ncurses.h file not found".  
<img width="1405" alt="screen shot 2017-12-24 at 11 01 22 pm" src="https://user-images.githubusercontent.com/8681183/34333101-a451de5a-e8fe-11e7-834b-e4789c16b294.png">

Log for tpf0 read fail: https://ghostbin.com/paste/xtupa

**Comment by ViroDaHaxr** [comment]
Just needed brew install ncurses

I am clearly an idiot. Let me be. But the tpf0 read fail is still an issue.

**Comment by lecopsportif** [comment]
Please check others issues before writing an other one.
#41
