### ISSUE TITLE
how do I uninstall cydia from my iPhone

### ISSUE THREAD

**Issue by yuzhouheike** [iabem97/topanga#48]
how do I uninstall cydia from my iPhone

**Comment by Counterassy** [comment]
you are not able to

**Comment by yuzhouheike** [comment]
thanks very much

**Comment by TimVanDenEnden** [comment]
hi guys a question

cydia is not loading right? this other app jjjj its this for handeling to get all the package?

**Comment by Counterassy** [comment]
jjjj seems to be a pretty promising cydia alternative and it‘s very light at least from what I‘ve seen

**Comment by reesretuta** [comment]
Sorry for the n00b question but how can someone get ssh access with jjjj? Is that even possible?

**Comment by Johntpeterson** [comment]
ret = run_path("/", (char **)&(const char*[]){"dpkg -P --force-depends cydia-lproj", NULL}, true);

?

**Comment by Johntpeterson** [comment]
@reesretuta To.panga has dropbear built-in.
