### ISSUE TITLE
OpenSource JJJJ?

### ISSUE THREAD

**Issue by Counterassy** [iabem97/topanga#50]
Hi,
i would like to play with the source code of jjjj, cause fun ... i guess :) 
can you create a git repo for it?

-----

btw. I know it's stupid to open an issue for that but I didn't find any message option within github and I don't have a twitter account XD

feel free to close this issue if it's unwanted by any means, 

thanks

**Comment by cvanelteren** [comment]
You have the internet right? https://github.com/rweichler/jjjj
