### ISSUE TITLE
jailbreak not working with iOS 11.0 for iphone 7 plus

### ISSUE THREAD

**Issue by kartikbilla007** [iabem97/topanga#54]
The jailbreak not working with iOS 11.0 for iphone 7 plus Proof: https://postimg.org/gallery/1upckojfq/

**Comment by Johntpeterson** [comment]
Post your logs.

It's untested for 7+.

**Comment by kartikbilla007** [comment]
thanks for your reply, how do I get the log data?

**Comment by Johntpeterson** [comment]
It's essentially impossible to debug without a MacOS machine. Also, I'd recommend deleting this app since it's not from a trusted repository. Best bet is to wait for the end user release.

**Comment by kartikbilla007** [comment]
Ok ya, what's the use when cydia isn't even working as it used to, I don't mind waiting now as there's not much difference between jailbroken and non jailbroken iOS 11 devices!

**Comment by Johntpeterson** [comment]
Impossible to debug w/o logs, needs closing.
