### ISSUE TITLE
Cydia Disappears 

### ISSUE THREAD

**Issue by Jamal-Hassan** [iabem97/topanga#55]
iPhone X iOS 11.1.2
When I open ToPanga App and Tap to Jailbreak,
It finishes the processing and Promptes as “finished” but cydia is not anywhere in the device

**Comment by bhupendpatil** [comment]
same on iPhone 6 iOS 11.1.2

**Comment by nillenalle4** [comment]
Same iphone 6s

**Comment by M3m0ryH4ck3r** [comment]
#1 Change line 266 in jailbreak.m, find if(should_install_cydia != YES), and change it to if(should_install_cydia == YES)

**Comment by nillenalle4** [comment]
You can't get xcode on windows
