### ISSUE TITLE
ncurses.h not found 

### ISSUE THREAD

**Issue by GeorgeLyurko2000ua** [iabem97/topanga#60]
I can't compile project because of this problem 
<img width="1278" alt="2017-12-26 2 55 20" src="https://user-images.githubusercontent.com/32428409/34343644-5fe40d48-e9e8-11e7-8354-351a0ad65276.png">

**Comment by Wh04m1cla33ic** [comment]
Build Setting: Search Paths -> /usr/local/opt/ncurses/include

**Comment by iabem97** [comment]
it was added by mistake
