### ISSUE TITLE
iPhone 7 Plus - 11.1.2 Cydia Missing D111AP

### ISSUE THREAD

**Issue by DarkK1d** [iabem97/topanga#7]
![Image](https://i.imgur.com/Zg05zgq.jpg)

![Image](https://i.imgur.com/FtZv69Q.jpg)

![Image](https://i.imgur.com/sguTA5I.jpg)

![Image](https://i.imgur.com/aNJ7XLA.jpg)

No Cydia...

**Comment by DarkK1d** [comment]
![Image](https://i.imgur.com/CYuEjX2.jpg)

![Image](https://i.imgur.com/zisD0fB.jpg)

**Comment by nullpixel** [comment]
Closed as a dupe of #1
