### ISSUE TITLE
Says finished but jjjj doesn't appear on the home screen

### ISSUE THREAD

**Issue by Brinkebrank** [iabem97/topanga#72]
log: https://pastebin.com/wNMkAaih

**Comment by Wh04m1cla33ic** [comment]
tried solution #29 ?

**Comment by Brinkebrank** [comment]
Yes it didn't work.

**Comment by Wh04m1cla33ic** [comment]
Which device are you using?

**Comment by Brinkebrank** [comment]
iPad Air

**Comment by MrBenFTW** [comment]
Hi, Close the app. Relaunch and try again. This took 3 tries but worked for me :)

**Comment by Brinkebrank** [comment]
Thanks that fixed it

**Comment by MrBenFTW** [comment]
Hi sorry to open the issue but if you now have JJJJ can you tell me if it actually works? Mine does not (iPhone x) 11.1.2
