### ISSUE TITLE
Question about erase

### ISSUE THREAD

**Issue by Uni9k** [iabem97/topanga#82]
My device is having problems.when i erase all content and settings on my iPhone X iOS11.1.2,then The system's own software is not available.

for example,when i touch Calendar icon ,that show " Unable To Install 'Calendar' "
This should be a permission issue.But I didn't find it.So I would like to ask you how to solve it.thank~:-)

![1](https://user-images.githubusercontent.com/10368342/34402384-22585b8c-ebdc-11e7-8762-4174bcda5d95.png)
![2](https://user-images.githubusercontent.com/10368342/34402385-2292b2fa-ebdc-11e7-8075-a898e1f0efd2.png)

**Comment by rnavalgund** [comment]
Some things you might consider doing.
1) run 'uicache' using terminal.
2) do a clean erase of your phone once again.
3) if you have shsh blobs, you can restore via futurerestore.

**Comment by Uni9k** [comment]
@rnavalgund I tried, it didn't work.

**Comment by Co2333** [comment]
Went to settings tap
-> General -> iPhone storage

Tap the app. Delete it and reinstall it from AppStore 

![eefbe23d-d89b-4a51-84da-9322dc6abb28](https://user-images.githubusercontent.com/25259084/34432602-b2c82df0-ecb3-11e7-9004-ef7a86e9a93d.jpeg)

**Comment by Uni9k** [comment]
@Co2333 没用 这要是有用的话 我就不会发了。。。唉 啥办法都试过了 肯定是这个app改了哪里的权限 我回去看看代码吧

**Comment by Co2333** [comment]
@Uni9k 这app改了launchdemos ， 加入了dylib注入器，也许是注入到springboard的dylib出问题了，但是不好乱改啊 我昨天删cydia和jjjj然后设置打不开了，然后springboard重启之后全部app打不开了。最后mess it up。现在在11.2

**Comment by Uni9k** [comment]
@Co2333 我有朋友是11.1.2的x也有那个filza 可以直接拷贝过来吗

**Comment by Co2333** [comment]
@Uni9k 别。你直接下载你当前系统版本的ipsw用mac解压然后找到最大的那个dmg直接挂载。你就有了所有系统文件。然后直接airdrop

**Comment by liudayu** [comment]
不用，你用Filza到 /etc/hosts里 把 
```
127.0.0.1	mesu.apple.com
```
这个删掉就能装系统应用了

**Comment by Uni9k** [comment]
@Co2333 已解决了。。。你楼下的大神厉害了

**Comment by Uni9k** [comment]
@liudayu 厉害了 谢谢大神！

**Comment by Uni9k** [comment]
@liudayu 大神 请问下 cydia不能联网这个怎么解决呢
![1](https://user-images.githubusercontent.com/10368342/34450045-7c56370c-ed3b-11e7-9ee7-9f30bf037d33.jpg)
![2](https://user-images.githubusercontent.com/10368342/34450048-857b2964-ed3b-11e7-82f6-ff75e33c512d.jpg)

**Comment by liudayu** [comment]
你要是不知道这个工具是干什么用的你就别瞎搞了好吧。。。

这个工具本身就不完整，cydia 在这个工具已经被 jjjj 替换，而且作者明确表示了cydia 不能联网，什么都不能干。

**Comment by Jacobwalton86** [comment]
I had this same problem and thanks to @liudayu its fixed now. I had to google translate this page a little as im reading in English but deleting the etc/hosts file fixed it for me
