### ISSUE TITLE
How can I removed jjjj APP

### ISSUE THREAD

**Issue by eamy001** [iabem97/topanga#90]
JJJJ Crash for my iPhone 7P, and I want to remove it ,How I Can do? Plase help me ,THX!

**Comment by Co2333** [comment]
Don’t do it. Just reinstall it. I had messed up my idevice because of removing Cydia and jjjj.

**Comment by eamy001** [comment]
T﹏T，but I dont like it because it dont work now，and panga program is stop now，so sad:(

**Comment by Co2333** [comment]
Because of the code sign is out of date. Reinstall.

**Comment by iabem97** [comment]
The above is incorrect. Removing Cydia/jjjj won't cause any "mess up". Both are just applications.
You can ssh into your device and run:
`rm -rf /Applications/jjjj.app`

or, although I can't recommend FilzaEscaped (I don't know what's in its code), you can install it and navigate to /Applications and remove jjjj.app

Please be careful and make sure you don't remove anything else.
