### ISSUE TITLE
Jailbreak finishes but Cydia doesn't appear

### ISSUE THREAD

**Issue by ConstantinosKoup** [iabem97/topanga#91]
I compiled the app on my device and when I run it, it seems to be working properly but after it finishes Cydia doesn't show up on my home screen. I searched for the error and I found that I should change line 266 from should_install_cydia != YES to should_install_cydia == YES, but line 266 now has should_install_jjjj != YES and even if I change it to should_install_jjjj == YES, it still does not work.
  
Edit: I have an iPhone 6 at ios 11.0

**Comment by RobertoTonini** [comment]
I’ve seen that on 25th December Cydia has been replaced. If I’m not wrong you can now use Houdini as an alternative to Cydia
